### ISSUE TITLE
Disprepancy in miRNA counts

### ISSUE THREAD

**Issue by trachtok** [lpantano/isomiRs#19]
Hi,

I would like to ask about some miRNA counts discrepancies I noticed when switching between different isomiRs versions. In past, I used isomiRs 1.10 and now I switched to isomiRs 1.16.2. I am fully aware there were many versions between and certainly many improvements that would affect the final miRNA counts, but I am seeing huge differences in quantified miRNA counts which are bothering me. For example, here is first 10 miRNAs counts produced by isomiRs 1.10 (output of function `IsomirDataSeqFromFiles()`):

```
                        METSEQ-T04 METSEQ-T05 METSEQ-T06 METSEQ-T07 METSEQ-T08 METSEQ-T09
"hsa-let-7a-2-3p"	16         3	      22	 1	    18	       1
"hsa-let-7a-3p"		444        436        807	 474	    564	       835
"hsa-let-7a-5p"		250567     211944     536064	 342337	    309013     339820
"hsa-let-7b-3p"		94         164	      531	 272	    104	       217
"hsa-let-7b-5p"		59497      70568      198727	 161083	    47276      114909
"hsa-let-7c-3p"		17         39	      83	 47	    22	       14
"hsa-let-7c-5p"		8253       24841      91330	 30526	    7284       12840
"hsa-let-7d-3p"		276        279	      937	 452	    483	       805
"hsa-let-7d-5p"		8848       6314	      17324	 13667	    16358      21746
```
and here by isomiRs 1.16.2:
```
                        METSEQ-T04 METSEQ-T05 METSEQ-T06 METSEQ-T07 METSEQ-T08 METSEQ-T09
"hsa-let-7a-2-3p"	8	   2	      10	 0	    15	       1
"hsa-let-7a-3p"	        346	   353        601	 349	    476	       636
"hsa-let-7a-5p"	        223211	   186839     468075	 293262	    275729     287835
"hsa-let-7b-3p"	        59	   88	      345	 144	    67	       123
"hsa-let-7b-5p"	        44572	   50948      147743	 115957	    33111      82647
"hsa-let-7c-3p"	        14	   35	      64	 38	    18	       12
"hsa-let-7c-5p"	        6589	   19765      73938	 23852	    5792       10195
"hsa-let-7d-3p"	        224	   220	      749	 276	    366	       623
"hsa-let-7d-5p"	        7069	   4855	      13515	 10135	    12969      15318
````

The difference is really big, if I sum it for each sample it gives even up to 1M, so I would like to know what is causing the difference. In issue #17, @svattathil mentioned that there is some noise filtering happening in IsomiRs, but I did not manage to find any information about it.

The problem might be related to the underlying issue of non-functioning conda isomiRs packages (latest versions) that I already posted [here](https://github.com/bioconda/bioconda-recipes/issues/26558). Specifically, the problem is probably in the changed syntax of `dplyr` package. I think so because when running isomiRs 1.16.2 `IsomirDataSeqFromFiles()` I got following warnings (for each input line, but the output table is produced):
```
1: Problem with `mutate()` input `prop`.
ℹ Chi-squared approximation may be incorrect
ℹ Input `prop` is `list(tidy(prop.test(value, total, pctco, alternative = "greater")))`.
ℹ The error occurred in row 6399.
```
I am using your great package a lot now and otherwise it does exactly what I need, so thank you for your work on this software so far :) I will very much appreciate it if you can look into this issue.

All the input/ouput files are [here](https://drive.google.com/drive/u/1/folders/107Du6BwaQtbDnFYUmDfNZcutv4x7aKAW).

Thank you!
Karolina

**Comment by lpantano** [comment]
Thank you for the detailed information, it helped a lot. I will need some time to dig into this. The main changes I introduced was in these parameters: `rate`, `canonicalAdd` and `uniqueMism`, you could try to put down rate=0, and maybe turn FALSE the other two. But not sure if that would do it only.

The error with the Chi-squared calculation is expected in some cases, and I think what changed is the package is displaying the error in this way now.

When you do differential expression do you get different results?

Thanks

**Comment by trachtok** [comment]
Hi, thank you for looking into this! I will try to change the parameters when running the newer version. I have not performed DE on the counts calculated by different isomiRs versions, but that's a good point and I will try to do it this week and let you know.

**Comment by trachtok** [comment]
Hi, so I finally had time to run the DE analysis on results of miraligner 3.5+isomiRs 1.10 and miraligner 3.5+isomiRs 1.16. For creating matrix of raw counts I used (in both cases) command:

`ids_xxx <- IsomirDataSeqFromFiles(fn_list, coldata=de, rate = 0, canonicalAdd = F, uniqueMism = F)`

The first thing I noticed is that the number of miRNA in the resulting matrix is not the same for both versions:
```
> nrow(assay(ids_116))
[1] 1532
> nrow(assay(ids_110))
[1] 2458
```
But when I looked at these extra ~800 miRNA from isomiRs 1.10, all but a few are extremely lowly expressed.

For the **DE analysis** I took some of our older QIAGEN smallRNA-seq data from tissue, altogether 89 samples so I can get nice results. The number of DE miRNAs (by DESeq2 1.28, padj < 0.05, FC > 1.5) was almost the same, but the specific DE miRNAs when using different isomiRs versions as input were different, see the Venn diagram below.

<img width="519" alt="Screenshot 2021-05-09 at 10 02 51" src="https://user-images.githubusercontent.com/22766694/117564725-c2440300-b0ad-11eb-9b8e-a20d6fcd73e2.png">

When I looked at the DE miRNAs that were the same for both isomiRs versions, the good thing I found is that their logFC is basically the same. What differs is of course baseMean (since IsomiRs 1.10 outputs much more reads for each miRNA than isomiRs 1.16) and p-values.

Top 5 miRNAs by DESeq2 when using isomiRs 1.10 vs isomiRs 1.16:
```
isomiRs 1.10
                  baseMean log2FoldChange     pvalue        padj
hsa-miR-200c-3p  57163.798       -7.25302  2.48082e-40 3.55006e-37
hsa-miR-141-5p    1643.386       -7.79934  2.84589e-38 2.03624e-35
hsa-miR-514a-3p   4123.324        8.23045  4.28257e-38 2.04278e-35
hsa-miR-200b-5p    533.445       -6.95016  1.19168e-36 4.26322e-34
hsa-miR-508-3p    2515.204        8.23256  7.88744e-36 2.25738e-33

isomiRs 1.16
                  baseMean log2FoldChange     pvalue        padj
hsa-miR-200c-3p  46245.425       -7.28447  6.89602e-40 7.53735e-37
hsa-miR-514a-3p   3359.712        8.30371  2.96679e-38 1.62135e-35
hsa-miR-200b-5p    413.604       -7.09510  1.61656e-37 5.88966e-35
hsa-miR-508-3p    2112.888        8.34415  6.49960e-37 1.66257e-34
hsa-miR-141-5p    1494.975       -7.80030  7.60556e-37 1.66257e-34
```
When I looked at some of the non-mutual DE miRNAs, I saw a lot of them that were assigned `NA` p-value by DESeq2 (probably due to having some of the samples marked as outliers) for one version of isomiRs but were ok with significant padj in the other version. Some miRNA simply did not reach the padj < 0.05 cutoff (had slightly higher than 0.05).

So I would say that the difference between isomiRs 1.10 vs 1.16 counts **is** affecting even DE analysis, although the top DE miRNAs are present whenever you use version 1.10 or 1.16. But for me, the discrepancy between counts is still kind of disturbing since when going through results of DE analysis, I always look also at normalized counts because miRNA with very low counts are usually hard to validate experimentally. 

Thanks for looking into this!

PS: I have uploaded the miraligner 3.5 output files, R script with isomiRs and DESeq2 commands and two .RData with results of `IsomirDataSeqFromFiles()` for both version of isomiRs package [here](https://drive.google.com/drive/folders/1bE4ZLxFxRc7AOz9EvF4FAF8tEL8zq2zj?usp=sharing). I installed the isomiRs 1.10 through Conda and isomiRs 1.16 locally since the Conda version does not work.

**Comment by trachtok** [comment]
Hi, thank you for looking into this, I put DESeq2 output for both isomiRs 1.10 and 1.16 into the shared google disk. Let me know if you need anything else!

**Comment by lpantano** [comment]
Hi, 

sorry it is taking me longer than expected, but I think I know where it is the change. I had some hard cutoff internally because it was the value was getting me lower FP according to some simulation data I was having. I will explain later tomorrow, and try to find a way to fix it to make it more consistent with previous versions.

Thanks for reporting though.

**Comment by trachtok** [comment]
Hi, not a problem, I know it takes some time to find a time for these things :) I will be looking forward to the explanation then and thank you once again for looking into this!

**Comment by lpantano** [comment]
Hi! can you try to install from master and see if now the same command gives similar values than the older version?

**Comment by trachtok** [comment]
Hi, so I installed the isomiRs 1.19 (`isomiRs_1.19.5`) using `install_github()` from devtools and run the same command as previously: `ids_119 <- IsomirDataSeqFromFiles(fn_list, coldata=coldata, rate = 0, canonicalAdd = F, uniqueMism = F)`. But what I see is actually even worse, there is much less read than in version 1.10 and 1.16, see below:

```
> head(mrcounts_110)
                METSEQ-T08 METSEQ-T20 METSEQ-T29 
hsa-let-7a-2-3p         18          2          9
hsa-let-7a-3p          579        927        879
hsa-let-7a-5p       317816      18695     387882
hsa-let-7b-3p          106        276        178
hsa-let-7b-5p        48695       4680      86204
hsa-let-7c-3p           22         40         53

> head(mrcounts_116)
                METSEQ-T08 METSEQ-T20 METSEQ-T29
hsa-let-7a-2-3p         15          2          7
hsa-let-7a-3p          476        695        689
hsa-let-7a-5p       275729      15067     337082
hsa-let-7b-3p           67        175        103
hsa-let-7b-5p        33111       2924      61713
hsa-let-7c-3p           18         34         44

> head(mrcounts_119)
                METSEQ-T08 METSEQ-T20 METSEQ-T29
hsa-let-7a-2-3p          1          8         16
hsa-let-7a-3p          181        553        451
hsa-let-7a-5p        59203     313751     257330
hsa-let-7b-3p           83        135         94
hsa-let-7b-5p        22782      94413      60570
hsa-let-7c-3p           20         49         17
```

And when I sum all raw counts for samples:
```
            raw_counts_ids110  raw_counts_ids116   raw_counts_ids119
METSEQ-T08            6051977            4449820             3290600
METSEQ-T20            2454364            1651073             5895149
METSEQ-T29            5737596            4270293             4647017
METSEQ-T33            8546280            6286063             3936965
METSEQ-T40            7078062            5273650             7398704
```

But now the effect (of the new 1.19 version) on the counts is rather chaotic, some libraries have more or almost the same number of reads as in version 1.10 (like samples METSEQ-T40) but some libraries have much less (like METSEQ-T08). 

Also, when I ran DE analysis with DESeq2 I got totally different results with 1.19 version in comparison to 1.10 and 1.16. I added the tsv table with DESeq2 results for version 1.19 into the google disk folder.

The overview of DE miRNAs (by DESeq2 1.28, padj < 0.05, FC > 1.5):
<img width="416" alt="image" src="https://user-images.githubusercontent.com/22766694/119824678-7343fd80-bef6-11eb-8caa-c6c75acd22b7.png">

So I think this did not work out or maybe I should change the parameters of the `IsomirDataSeqFromFiles()`?

**Comment by lpantano** [comment]
mm, some weird things here.

- When I use two samples to test the code in the master branch I get similar to 1.10

```
s = c("METSEQ-T08", "METSEQ-T20")
de <- data.frame(row.names=s,
                condition = c("one", "one"))
ids <- IsomirDataSeqFromFiles(file.path("~/Downloads/isomiRs_test/miraligner3.5", paste0(s,"_SE.mirna")),
                              coldata=de,
                              rate = 0, canonicalAdd = F, uniqueMism = F)

head(counts(ids))

                METSEQ-T08 METSEQ-T20 METSEQ-T29
hsa-let-7a-2-3p         18          2          9
hsa-let-7a-3p          579        927        879
hsa-let-7a-5p       317816      18695     387882
hsa-let-7b-3p          106        276        178
hsa-let-7b-5p        48695       4680      86204
hsa-let-7c-3p           22         40         53

> colSums(counts(ids))
METSEQ-T08 METSEQ-T20 METSEQ-T29 
   6051977    2454364    5737596 
```

- I get similar to 1.6 if I do this (remove rate from the options, that was part of the problem):
```
ids116 <- IsomirDataSeqFromFiles(file.path("~/Downloads/isomiRs_test/miraligner3.5", paste0(s,"_SE.mirna")),
                              coldata=de, canonicalAdd = F, uniqueMism = F)
head(counts(ids116))

                METSEQ-T08 METSEQ-T20 METSEQ-T29
hsa-let-7a-2-3p         15          2          5
hsa-let-7a-3p          364        424        456
hsa-let-7a-5p       233258      11355     273272
hsa-let-7b-3p           56        131         77
hsa-let-7b-5p        21877       1653      38129
hsa-let-7c-3p           15         34         36
```

how was the command to install from github?

Thanks!

**Comment by trachtok** [comment]
Hi, well that was in the end my mistake, I was not downloading from the master even though I thought I was, sorry! You are right, the isomiRs version from master is now giving the same results as isomiRs 1.10 and when I remove `rate` parameter from the `IsomirDataSeqFromFiles()` I get similar results to isomiRs 1.16. So the change you made works.

My question is now what exactly was the change between 1.10 and 1.16 that caused the results of `IsomirDataSeqFromFiles ()` to be different (even though results of DE were very similar with both versions, absolute number of reads for each miRNA was quite different, version 1.16 overall reported less reads for each miRNA than 1.10). I am now not sure how to set the parameters of `IsomirDataSeqFromFiles()` so that I will get the most accurate results in terms of both miRNA counts and subsequent DE analysis.

Thank you once again for your work on this!

**Comment by lpantano** [comment]
I am trying to find some time to reply this appropriately. The main reason was that 1.10 there was no cutoff to consider all the reads mapping to a mirna part of the mirna. In 1.16, I implemented a hard cutoff, sequences with < 1% of the total mirna expression will be considered error sequencing. Then I updated to a probabilistic cutoff. I calculate if the frequency of each sequence is statistically significant higher than 1%, and if not filter it out. 1.19 had a bug, because I was filtering twice, mainly losing the lower tail of sequences mapping a miRNA. Now it is kind of fixed, I think. 

Under my experience, I think is good to filter out those sequences, if you are analyzing isomiRs. I will go with the current version to avoid double filtering due to the bug. If you are interested in miRNAs (adding up all sequences), it should be more or less the same, only maybe for the low expressed miRNAs, where there could be some bias because of being part of the noisy distribution. Another option I like to do, it is go with the top 3 sequences for each miRNA when doing DE. According to my experience, normally, 2-4 isomiRs are the most represented for each miRNA. But it is difficult to make a rule for all situations.

I think, if you stay at the miRNA level, you can leave rate at 0, and probably your results should be fine. Another very different answer would be for isomiRs analysis though. I hope this help somehow, I know it is not a nice answer...

**Comment by trachtok** [comment]
Hi, thanks for explaining, now I have a better picture of what is happening :) I am most often interested in miRNA (not specific isomiRs) although in my recent project I was examining isomiRs content as well. So I will go with the newest version of the isomiRs package. Thank you for finding time to look into this issue and for explaining the logic behind it.
