### ISSUE TITLE
IsomirDataSeqFromFiles error 

### ISSUE THREAD

**Issue by hmkim** [lpantano/isomiRs#2]
```
> obj <- IsomirDataSeqFromFiles(files = files[rownames(design)], design = design , header = T)
Error in initialize(value, ...) : 
  cannot use object of class “SummarizedExperiment0” in new():  class “IsomirDataSeq” does not extend that class
```

Hi, Ipantano

Would you give me any suggestion about this error ?

**Comment by lpantano** [comment]
hum, can you send me the sessionInfo() output? I think is a problem of version. Did you install the package recently? 

sent not from my computer

**Comment by lpantano** [comment]
can you check to install again this package from github origin/master. I think is a problem with summarixedexperiment object and maybe I fixed it.

thanks

**Comment by hmkim** [comment]
Ok. I'll try to run again and report it.

**Comment by hmkim** [comment]
Sorry for delaying my reply.

I solve the before problem.

I have another issue about this function in Isomir.

`obj_mirdeep <- IsomirDataSeqFromFiles(files = files[rownames(design)], design = design , header = TRUE)`

```
> design
     type batch phenotype
PK_1   PK  None        PK
PI_1   PI  None        PI
PI_2   PI  None        PI
SI_1   SI  None        SI
SI_2   SI  None        SI
SK_1   SK  None        SK
```

```
> files[rownames(design)]
                                                               PK_1 
"/Users/brandon/Downloads/work/upload/PK_1/PK_1-novel-ready.counts" 
                                                               PI_1 
"/Users/brandon/Downloads/work/upload/PI_1/PI_1-novel-ready.counts" 
                                                               PI_2 
"/Users/brandon/Downloads/work/upload/PI_2/PI_2-novel-ready.counts" 
                                                               SI_1 
"/Users/brandon/Downloads/work/upload/SI_1/SI_1-novel-ready.counts" 
                                                               SI_2 
"/Users/brandon/Downloads/work/upload/SI_2/SI_2-novel-ready.counts" 
                                                               SK_1 
"/Users/brandon/Downloads/work/upload/SK_1/SK_1-novel-ready.counts" 
```

Can you check this error?

**Comment by lpantano** [comment]
Hi,

what is the error you are getting? 


sent not from my computer

**Comment by hmkim** [comment]
sorry, I rerun the report scripts in bcbio of last development. It has no problem.

**Comment by hmkim** [comment]
obj_mirdeep <- IsomirDataSeqFromFiles(files = files[rownames(design)], design = design , header = T)
Error in if (row["subs"] == "0") return(c(.seq, row["subs"])) else if (sum(tab.fil$subs ==  : 
  missing value where TRUE/FALSE needed

**Comment by lpantano** [comment]
Can you check this code to isolate what file is giving the error:

```
obj_mirdeep <- IsomirDataSeqFromFiles(files = files[rownames(design)], design = design , header = T, quiet=False)
```

Also, can you paste the few lines of some of the file is reading, just in case there is something obvious.

**Comment by hmkim** [comment]
```
> obj_mirdeep <- IsomirDataSeqFromFiles(files = files[rownames(design)], design = design , header = T, quiet=False)
Error: object 'False' not found

```

## novel miRNA by mirdeep2

### total miRNA expression

```{r mirdeep2,results='hide', eval=ismirdeep2}
files = mirdeep2_files

names(files) = sapply(files, function(x){
  gsub("-novel-ready.counts", "", basename(x))
})

#obj_mirdeep <- IsomirDataSeqFromFiles(files = files[rownames(design)], design = design , header = T)
obj_mirdeep <- IsomirDataSeqFromFiles(files = files[rownames(design)], design = design , header = T, quiet=False)

```

If you want to any data related to this problem, please tell me about that.

Thanks!

**Comment by lpantano** [comment]
sorry, it should be FALSE

let me know the output. Then if we get one file is failing maybe you can sending me file to my email.

thanks

sent not from my computer

**Comment by hmkim** [comment]
I might find the cause of problem. 

If some samples don't have the novel miRNA, it is badly for IsomirDataSeqFromFiles.

[design2] have only SI_1, SI_2 and SK_1 sample.

obj_mirdeep <- IsomirDataSeqFromFiles(files = files[rownames(design2)], design = design2 , header = T)

![2016-05-31 15 44 36](https://cloud.githubusercontent.com/assets/4966343/15665673/43eac7cc-2747-11e6-9b2a-8632a5bc7351.png)

**Comment by simonas-j** [comment]
Hi Ipantano,

I'm getting the same error and I have no clue what could cause it. See the code below:

> head(metafile, n=2)
      Condition
D1416      GIST
D1417    GISTaj

> head(files.list, n=2)
                                                             D1416 
"/home/simonas/Results/isomir_D1416.mirna" 
                                                             D1417 
"/home/simonas/Results/isomir_D1417.mirna" 

> ids <- IsomirDataSeqFromFiles(files.list, design=metafile, header = TRUE, quiet= FALSE)
reading file:  /home/simonas/Results/isomir_D1416.mirna 
Error in if (row["subs"] == "0") return(c(.seq, row["subs"])) else if (sum(tab.fil$subs ==  : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In .put_header(table) : NAs introduced by coercion

> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.1 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] stringr_1.1.0              isomiRs_1.1.5              SummarizedExperiment_1.2.3 Biobase_2.32.0             GenomicRanges_1.24.3       GenomeInfoDb_1.8.7        
 [7] IRanges_2.6.1              S4Vectors_0.10.3           BiocGenerics_0.18.0        DiscriMiner_0.1-29        

loaded via a namespace (and not attached):
 [1] genefilter_1.54.2    gtools_3.5.0         locfit_1.5-9.1       splines_3.3.1        lattice_0.20-34      colorspace_1.2-7     chron_2.3-47         survival_2.39-5     
 [9] XML_3.98-1.4         foreign_0.8-67       DBI_0.5-1            BiocParallel_1.6.6   RColorBrewer_1.1-2   plyr_1.8.4           zlibbioc_1.18.0      munsell_0.4.3       
[17] gtable_0.2.0         caTools_1.17.1       DESeq2_1.12.4        latticeExtra_0.6-28  GGally_1.2.0         geneplotter_1.50.0   AnnotationDbi_1.34.4 Rcpp_0.12.7         
[25] KernSmooth_2.23-15   acepack_1.3-3.3      xtable_1.8-2         readr_1.0.0          scales_0.4.0         gdata_2.17.0         Hmisc_3.17-4         annotate_1.50.1     
[33] XVector_0.12.1       gplots_3.0.1         gridExtra_2.2.1      ggplot2_2.1.0        stringi_1.1.2        dplyr_0.5.0          grid_3.3.1           tools_3.3.1         
[41] bitops_1.0-6         magrittr_1.5         lazyeval_0.2.0       RCurl_1.95-4.8       tibble_1.2           RSQLite_1.0.0        Formula_1.2-1        cluster_2.0.5       
[49] tidyr_0.6.0          Matrix_1.2-7.1       data.table_1.9.6     assertthat_0.1       reshape_0.8.5        R6_2.2.0             rpart_4.1-10         nnet_7.3-12         

Thank you in advance!

**Comment by lpantano** [comment]
Hi,

sorry about this. 

can you send me one of the files so I can make sure is not a problem of isomiRs version. You can try to install to last version of the package but I think 1.1.5 was the one that fixed this error.

thanks!

**Comment by simonas-j** [comment]
Sorry, for disturbing you. I fixed the problem. I didn't have frequencies in miraligner's .mirna file which caused the problem.

**Comment by lpantano** [comment]
Let me know if you have more issues in the future
