### ISSUE TITLE
error with IsomirDataSeqFromFiles

### ISSUE THREAD

**Issue by gnvalbuena** [lpantano/isomiRs#3]
Hi,

I am coming up with an error when I try to import the data from files. I was wondering if you had any information on why this particular error might be coming up?

```
obj <- IsomirDataSeqFromFiles(filelist, design=design, header=T, quiet=FALSE)

Error in if (tab.fil$ratio[tab.fil$subs == row["subs"] & tab.fil$mir ==  : 
  argument is of length zero
```

Thanks!

Gabriel

**Comment by lpantano** [comment]
Hi,

sorry about this.

The quicker way to solve this is to send me the files. If there are a lot, you can try the command one by one and get the file that is producing the error. Then you can send me the error to me, and I can debug further. Normally this are edge cases in isomiR annotation, and from time to time I discover a new one.

thanks

**Comment by gnvalbuena** [comment]
Hi Lorena,

There are a lot of files, so I've narrowed it down to a couple of offending ones. I've sent the files to you separately through your listed email. The relevant error messages for both are as follows:

```
> obj2 <- IsomirDataSeqFromFiles(isomirfilelist[68], design=isomirdesign[68,], header=T)
Error in if (tab.fil$ratio[tab.fil$subs == row["subs"] & tab.fil$mir ==  : 
  argument is of length zero
> obj2 <- IsomirDataSeqFromFiles(isomirfilelist[184], design=isomirdesign[184,], header=T)
Error in if (tab.fil$ratio[tab.fil$subs == row["subs"] & tab.fil$mir ==  : 
  argument is of length zero
```

Thanks!

Gabriel

**Comment by lpantano** [comment]
Thanks, let’s see what I find!

**Comment by lpantano** [comment]
can you try to update the package from bioconductor?

you can get the dev version with devtools::install_git("Bioconductor-mirror/isomiRs”)

let me know if that fixes.

**Comment by gnvalbuena** [comment]
Sorry, that command doesn't seem to be working for me on R. It seem to think that `devtools::install_git("Bioconductor-mirror/isomiRs”)` is incomplete. Is there anything else that I need to include?

**Comment by lpantano** [comment]
sorry is devtools::install_github

**Comment by gnvalbuena** [comment]
sorry, that still doesnt seem to work for me when I type in devtools::install_github("Bioconductor-mirror/isomiRs”)

**Comment by lpantano** [comment]
what is the error?

**Comment by gnvalbuena** [comment]
R moves to the next line with + and is waiting for the command to be
completed

**Comment by lpantano** [comment]
ops, make sure that the quotation are straight quotations. macosx sometimes put smart quotations instead that are curved. 

maybe you can type them instead of copy/paste

sent not from my computer

**Comment by gnvalbuena** [comment]
Hi Lorena,

Sorry about that. looks like that seems to have done the trick for those two files. Just giving it another test now. What was the issue that it wasn't coping well with?

**Comment by lpantano** [comment]
Somebody reported this error a while ago and I fixed it. I thought this was a new error, since every sample is different … difficult to know what is the same error or not. I tried your files with my last dev version and it worked, so I guessed you were using a previous version. 

Tomorrow, Bioconductor is moving to new release so this error should be all gone for all version.

let me know if you find any other error.

thanks

**Comment by gnvalbuena** [comment]
Thanks!

Just to note though that when using the dev version, it prints out 

`Parsed with column specification:
cols(
  seq = col_character(),
  name = col_character(),
  freq = col_integer(),
  mir = col_character(),
  start = col_integer(),
  end = col_integer(),
  mism = col_character(),
  add = col_character(),
  t5 = col_character(),
  t3 = col_character(),
  s5 = col_character(),
  s3 = col_character(),
  DB = col_character(),
  precursor = col_character(),
  ambiguity = col_integer()
)`

after every file read, even when quiet=TRUE

**Comment by lpantano** [comment]
Thanks u. Yes is the new version of readr package needs to find out how to change that.

**Comment by gnvalbuena** [comment]
Hi Lorena,

Just an unrelated question. I've run seqcluster on bcbio on aws, and just wanted to ask and check, which version of mirbase is being used for annotation? Thanks!

**Comment by lpantano** [comment]
Hi,

it should be mirbase 21.

thanks for the question!

sent not from my computer

**Comment by lpantano** [comment]
Let me know if you have more issues in the future.
