### ISSUE TITLE
isomiRs annotation

### ISSUE THREAD

**Issue by jsimonas** [lpantano/isomiRs#4]
Hi,

Thank you a lot for such a nice package! However, I didn't understand how isomiRs are annotated.  In the example of the vignette (which is below) there are two miRNAs which have the same 5' modification (**) but one is named ref. and another named iso. So why the molecule having modification is named as ref? And why they do not share the same name even though the modification is the same?

```
dds = isoDE(ids, formula=~condition, ref=TRUE, iso5=TRUE)
head(results(dds, tidy=TRUE))

   row                         baseMean   log2FoldChange lfcSE     stat        pvalue
1  hsa-let-7a-3p.iso.t5:0      18.174659  -0.0147846     0.5485291 -0.02695318 0.9784971
2  hsa-let-7a-3p.iso.t5:c      3.48228     0.7353251     0.8043144  0.91422589 0.3605982
3  **hsa-let-7a-3p.iso.t5:ct   4.148260    0.4996872     0.7783157  0.64201102 0.5208660
4  hsa-let-7a-3p.ref.t5:0      7.052740   -0.2545893     0.6761882 -0.37650660 0.7065403
5  hsa-let-7a-3p.ref.t5:c      4.231561    0.2260381     0.7555882  0.29915509 0.7648217
6  **hsa-let-7a-3p.ref.t5:ct   1.192198   -0.3630919     0.8902994 -0.40783118 0.6833976 
```

**Comment by lpantano** [comment]
Hi,

sorry about this. I caught a bug two weeks ago, and I push a fix for the development version.

Can you tell me what version are you using right now? You can upload the last one with devtools package from the GitHub https://github.com/Bioconductor-mirror/isomiRs <https://github.com/Bioconductor-mirror/isomiRs>.

devtools::install_github("Bioconductor-mirror/isomiRs”)

In the next day the next stable version comes up in Bioc and should be this version, that’s the reason I didn’t fix the stable directly.

Let me know, and sorry for the issue.

**Comment by jsimonas** [comment]
Yes, I was outdated, I had the one which is on Bioc (v1.2.0), now everything works fine! 
Thank you a lot! And thanks for the new features in the current version!
